---
title: "K-Medias datos iris"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
library(datasets)
data(iris)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('xcol', 'Variable X', names(iris))
    
selectInput('ycol', 'Variable Y', names(iris),
                selected=names(iris)[[2]])
    
numericInput('clusters', 'Nº Clusters', 3,
              min = 1, max = 9)
```

Column
-----------------------------------------------------------------------

### K Means

```{r}
palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

selectedData <- reactive({
  iris[, c(input$xcol, input$ycol)]
})

clusters <- reactive({
  kmeans(selectedData(), input$clusters)
})

renderPlot({
  par(mar = c(5.1, 4.1, 0, 1))
  plot(selectedData(),
       col = clusters()$cluster,
       pch = 20, cex = 3)
  points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
})
```

